version: '3.8'

services:
  zalo-webhook:
    build: .
    # Không expose port ra ngoài, chỉ chạy internal
    ports:
      - "127.0.0.1:8001:8000"  # Chỉ bind localhost, port 8001
    environment:
      - PORT=8000
      - DEBUG=False
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - webhook-network

  # Optional: Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "127.0.0.1:6379:6379"  # Chỉ bind localhost
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - webhook-network

  # Optional: PostgreSQL database
  # postgres:
  #   image: postgres:15-alpine
  #   ports:
  #     - "127.0.0.1:5432:5432"  # Chỉ bind localhost
  #   environment:
  #     POSTGRES_DB: zalo_webhook
  #     POSTGRES_USER: webhook_user
  #     POSTGRES_PASSWORD: your_password_here
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - webhook-network

networks:
  webhook-network:
    driver: bridge

# volumes:
#   redis_data:
#   postgres_data:
